services:
  roleta2_backend:
    container_name: roleta2_backend
    build:
      context: ./roleta2/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    networks:
      - rede_externa

  roleta2_frontend:
    container_name: roleta2_frontend
    build:
      context: ./roleta2/
      dockerfile: ./src/Dockerfile
    ports:
      - "81:81"
    depends_on:
      - roleta2_backend
    restart: unless-stopped
    networks:
      - rede_externa

  cloudflared:
    container_name: roleta2_tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --protocol http2 run --token eyJhIjoiOGQ2YTZmYWY4YzMwM2EzNDU2YzNlZDUwMGYzNjBlNDciLCJ0IjoiYjg0YzFmNTgtNDMzMi00MWQ5LTg5NjAtZDIzM2FhYTdjYWRmIiwicyI6Ik1UTmlPR1V4WVRVdE1HRmxOaTAwTlRNeUxUbGlPRFV0T0RJMk9XRXhZVEEwTWpKbE1UQmxaakk0TldZdE56WTVNeTAwTVRNeExXSmlZamd0TTJZd016WXhZakpoWlRnNSJ9
    restart: unless-stopped
    networks:
      - rede_externa

networks:
  rede_externa:
    external: true
    name: rede_externa